### ISSUE TITLE
"Package gs-esp is not installed"

### ISSUE THREAD

**Issue by CyberShadow** [raducotescu/CanonCAPTdriver#1]
The Canon driver deb files specify a dependency on the "gs-esp" package.

However, that package has been removed, and is not present in current releases of Ubuntu and Mint. Thus, the script fails to install these packages.

Additionally, lack of error handling in the script causes it to continue anyway, and result in a broken installation. Considering adding `set -e` to your script.

I have modified the script to add `--ignore-depends=gs-esp` to the `dpkg` commands. This fixed the dpkg installation.

**Comment by raducotescu** [comment]
Can you please provide a pull request?

**Comment by CyberShadow** [comment]
I could, but a proper fix would be more involved than just adding the flag. Ideally it should check if the package `gs-esp` is installable, and if not, install the `ghostscript-x` package first (as it seems that's what replaced `gs-esp`).

Also, I don't know what the impact of adding the error handling switch would have. Perhaps some commands are expected to "fail" (return a non-zero exit code). I don't know enough about the script in general to know that.

There's also another possible issue, with the script assuming that the distribution is Ubuntu, even though its goal seems to be to cover Debian-based systems? The issue is that `lsb_release -r` prints a version number specific to the current distribution, and it is compared against "9.10", which is an Ubuntu release number.

**Comment by raducotescu** [comment]
The script was designed for Ubuntu, when I was using that OS: http://radu.cotescu.com/how-to-install-canon-lbp-printers-in-ubuntu/

Since I'm not running Ubuntu anymore I've stopped updating the script to cater for newer Ubuntu releases. However anyone is free to provide a pull request or to fork the code. :)

**Comment by CyberShadow** [comment]
OK, I was going from the comment at the top of the script. But looking at it again, it appears I've misread it, as it was the Canon driver that targets Debian-based Linux systems.

**Comment by hrj** [comment]
@CyberShadow Did you have success in configuring your printer with Ubuntu 12.10 64 bit?

I can get it to work fine on Ubuntu 12.04 32bit, but not on the 12.10 64 bit version. Before exploring further wanted to know if it was atleast known to work.

**Comment by CyberShadow** [comment]
No :( It was actually Linux Mint, and for someone else. I gave up, and just told them that their printer was too old for their computer and told them to buy another printer, not Canon.
